import random
n=int(input('Cate valori sa aiba tuplul?= '))
tuplu_numere=tuple(random.randint(-100,100)for i in range(n)) 
print('Tuplul generat este:')
print(tuplu_numere)
print('Primul e',tuplu_numere [0])
print('Ultimul e',tuplu_numere [-1])
print('Lungimea tuplului=',len(tuplu_numere),'elemente')
print('Suma e',sum(tuplu_numere))
print('Valoare maxima e', max(tuplu_numere))
print('Valoare minima e', min(tuplu_numere))
print('Sortarea crescatoare e',sorted(tuplu_numere))
print('Sortarea descrescatoare e', sorted(tuplu_numere))
neg=sum(1 for tuplu_numere in tuplu_numere if tuplu_numere<0)
print('Valorile nagative sunt', neg)
poz=sum(1 for tuplu_numere in tuplu_numere if tuplu_numere>0)
print('Valotile pozitive sunt',poz)
